ERR 1.2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,6 +43,7 @@ jobs:
             echo "Deployment failed, sending cURL request..."
             echo "Success ${{job.status}}"
             curl http://137.184.137.85:5001/api
+            echo "This is an error message" >&2
 
       - name: Send cURL Request on Success
         if: success()
